on:
    push:
        branche: [develop-*]
jobs:
  build_web3_feed:
    runs-on: ubuntu-latest
    name: Build web3-feed
    steps:
      ## NOTE: https://github.com/actions/checkout/issues/24#issuecomment-525547275
      - uses: actions/checkout@master
        with:
          name: icasimpan/ismael.casimpan.com.git
          repository: icasimpan/ismael.casimpan.com.git
          ref: refs/heads/master
      - name: Docker Build
        id: dockerbuild
        uses: icasimpan/feeds@master
