on: [push]

jobs:
  web3-feed:
    runs-on: ubuntu-latest
    name: Backup and replace web3-feed.md
    steps:
      - name: Create the web3-feed.md markdown
        id: web3-feed-creation
        uses: icasimpan/feeds@master
