on:
    push:
        branche: [develop-*]

jobs:
  build_web3_feed:
    runs-on: ubuntu-latest
    name: Build web3-feed
    steps:
      - name: Docker Build
        id: dockerbuild
        uses: icasimpan/feeds@master
